version: '3.8'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      RAILS_ENV: development
    networks:
      - music-app-network

  db:
    image: mysql:8.0.32
    container_name: music-app-db
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=music_app
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    networks:
      - music-app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: music-app-pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8081:80'
    networks:
      - music-app-network

networks:
  music-app-network:
    driver: bridge
